### ISSUE TITLE
Requires dotnet 5.

### ISSUE THREAD

**Issue by megafluffles** [BorisWilhelms/create-dotnet-devcert#3] opened 2021-02-22 00:33 UTC
Hi, I think this just needs to be added to the prerequisites. Version 3.1 of dotnet dev-certs https doesn't support the --import option as best I can tell.

**Comment by sarvasana** [comment] 2021-02-22 08:01
Correct, I ran into that as well. If someone does not know that, they are puzzled. 
Better to mention it.

**Comment by hugbro** [comment] 2021-03-27 02:51
Stuck on this as well. Maybe is this a workaround for dotnet 3.1?

**Comment by sarvasana** [comment] 2021-03-28 06:12
> Stuck on this as well. Maybe is there a workaround for dotnet 3.1?

Install net5, use net31.

**Comment by hugbro** [comment] 2021-03-28 16:08
Well, I felt like an idiot now 😆. Thank you.

**Comment by sarvasana** [comment] 2021-04-01 15:19
Wow, I just installed a new machine (manjaro) and am having issue with running `dotnet dev-certs https`.

Got net5 installed. 
Could not find the dotnet tool.
Ran `dotnet tool install --global dotnet-dev-certs`

Now `dotnet dev-certs https` does not support the `--import` argument.

What is going on?

**Comment by sarvasana** [comment] 2021-04-02 09:48
I ran into more problems when using the `dotnet-install.sh` script.
Problems I had were:

- MSBuild.Sdk.SqlProj could not find `dotnet`
- Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(37, 5): Metadata generation failed. Exit code: '134' Error: 'No usable version of the libssl was found'

This was most likely caused because `dotnet` got installed at `~/.dotnet`.

The solution that does work is:
`sudo ./dotnet-install.sh -c Current --install-dir /usr/share/dotnet`
`sudo ./dotnet-install.sh -c LTS --install-dir /usr/share/dotnet`
`sudo ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet`

**Comment by abrahamlaria** [comment] 2021-05-05 06:03
Hello,
I'm using Ubuntu and I installed the certificate following the pre requisites. Still when trying to run an asp.net core 5.0 application the browser says it is not secure. In Rider it doesn't even open the browser and stop program. In VS Code it starts listening on https://localhost:5001 but it doesn't open any browser as well. Entering the URL directly on the browser shows the not secure warning.
Am I missing something?
Thanks!

**Comment by sarvasana** [comment] 2021-05-05 09:07
In the browser you can simply trust the certificate by using the rendered warning page.

The other issues are probably caused by incorrect launchsettings.
I would check those.

**Comment by abrahamlaria** [comment] 2021-05-05 16:30
Thanks, I got it to work :)

**Comment by BorisWilhelms** [comment] 2021-06-27 13:39
Good point. Yes, `dotnet dev-certs https --import` needs .NET 5. I will update the README and add this to the prerequisites. 

While it is technically possible to add the cert to .NET Core 3.1 SDK, I am not a bash specialist and don't know how to check and add this. 

If someone is willing to this contact me and we can discuss this.

**Comment by BorisWilhelms** [comment] 2023-04-03 15:11
I guess we can close this. .NET 3.1 and .NET 5 are EOL and out of support.

**Closed by BorisWilhelms** 2023-04-03 15:11 UTC
Labels: help wanted
